name: flutter_clean_architecture_skeleton
description: Flutter Clean Architecture Skeleton

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  # State
  flutter_bloc: ^8.1.1
  
  # Equality
  equatable: ^2.0.5

  # Navigation
  go_router: ^6.0.0

  # Form Operations and Validations
  formz: ^0.4.1

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Responsive
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation 
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

